name: 'Configure K8s context'
description: 'Configure Kubeconfig to easily authenticate using service account token'
inputs:
  server:
    description: K8s server endpoint
    required: true
  token:
    description: base64 encoded service account token
    required: true
  ca:
    description: base64 encoded ca cert
    required: true
  user:
    description: name of the service account
    required: false
    default: jenkins

branding:
  color: 'purple'


runs:
  using: "composite"
  steps:
  - name: Configure Kubeconfig
    run: |
      echo "${{ inputs.ca }} > ./ca.crt" && \
      kubectl config set-context \
        current \
        --user=gha \
        --certificate-authority=./ca.crt \
        --server=${{ inputs.server }} \
        --token=${{ inputs.token }} \
        --username=${{ inputs.user }} && \
      kubectl config use-context current

    shell: bash